### ISSUE TITLE
Doesn't seem to handle #! lines

### ISSUE THREAD

**Issue by russel** [Hackerpilot/dfmt#101]
I have the code:

```d
#! /usr/bin/env rdmd

import std.stdio: writeln;

int main(immutable string[] args) {
  writeln("Hello World!");
  return 0;
}
```
if I run "dfmt -t --braces=otbs" on the code I get:
```d
#! /usr/bin/env rdmdimport std.stdio : writeln;

int main(immutable string[] args) {
writeln("Hello World!");
return 0;
}
```
which destroys the #! and the import. I also note no tabs are being emitted for the indentation, should this be a separate issue?

**Comment by Hackerpilot** [comment]
There were two issues here, one of them that I haven't tested with script lines, and the other that my new indentation code wasn't tested with both brace styles.

**Comment by Hackerpilot** [comment]
I've added tests for --braceStyle=otbs output, so this shouldn't break in the future.

**Comment by russel** [comment]
Looks good to me, thanks for getting done quickly :-) However, there is another issue… new issue to be created.
