### ISSUE TITLE
Space before colon in imports

### ISSUE THREAD

**Issue by russel** [Hackerpilot/dfmt#102]
I have the code:
```d
#! /usr/bin/env rdmd

import std.stdio: writeln;

int main(immutable string[] args) {
  writeln("Hello World!");
  return 0;
}
```
if I run "dfmt -t --braces=otbs" on the code I get:
```d
#! /usr/bin/env rdmd

import std.stdio : writeln;

int main(immutable string[] args) {
	writeln("Hello World!");
	return 0;
}
```
which is fine except that an unexpected space has been inserted after std.stdio, should this be controllable?

**Comment by Hackerpilot** [comment]
This is now implemented. You can check out the 0.4.0 branch if you'd like to try it.
