### ISSUE TITLE
Concatenated strings on different lines are sometimes put on the same line

### ISSUE THREAD

**Issue by MetaLang** [Hackerpilot/dfmt#110]
Before dfmt:

    wrapWriteln("This question set is about " ~ questionSet["focus"].str ~ ". "
                            ~ `Type "hint" to get a hint for the current question. `
                            ~ `Type "question" to see the question again. `
                            ~ `Type "skip" to display the answer and go to the next question. `
                            ~ `Type "skip set" to skip this question set. `
                            ~ `Type "quit" to quit.`);

After dfmt:

    wrapWriteln("This question set is about " ~ questionSet["focus"].str ~ ". "
                ~ `Type "hint" to get a hint for the current question. `
                ~ `Type "question" to see the question again. `
                ~ `Type "skip" to display the answer and go to the next question. `
                ~ `Type "skip set" to skip this question set. ` ~ `Type "quit" to quit.`);

Note the difference in the last line.

**Comment by Hackerpilot** [comment]
How should dfmt know that your code is special?

**Comment by MetaLang** [comment]
What do you mean? Isn't this considered a bug if it put every other string on its own line except for the last one?

**Comment by Hackerpilot** [comment]
All of the other strings are long enough that they won't fit on the same lines, but the last two are short enough that they can.

**Comment by MetaLang** [comment]
Okay, I didn't realize it was due to line wrapping.
