### ISSUE TITLE
Inconsistent indenting and spacing with function literals

### ISSUE THREAD

**Issue by biozic** [Hackerpilot/dfmt#119]
Before:
```d
auto fun = function() {};
auto fun = () {};
auto fun = {};

auto fun = {int i;};

auto fun = {int i;int i;int i;int i;};
```

After:
```d
auto fun = function() {  };
auto fun = () {  };
auto fun = {};

auto fun = { int i;  };

auto fun = { int i;
int i;
int i;
int i;  };
```

**Comment by Hackerpilot** [comment]
Are you sure that some of those aren't struct literals?

**Comment by biozic** [comment]
Right, `{}` is a struct initializer (not literal). The others are function literals, aren't they?

**Comment by Hackerpilot** [comment]
The fact that you're not sure is more evidence that this function syntax was a mistake. I'm going to try handling function literals with the code that currently handles array initializers. Maybe that will give better results.

We wouldn't have this problem if some braces weren't more special than others.
