### ISSUE TITLE
support for .editorconfig

### ISSUE THREAD

**Issue by MartinNowak** [Hackerpilot/dfmt#122]
[EditorConfig](http://editorconfig.org/) is a cross-editor format to specify basic formatting.
It would be nice if dfmt could read those files and use them to automatically switch between tabs and spaces, different indent size, et.al.

**Comment by MartinNowak** [comment]
It could also be used to configure other dfmt settings, such as the brace style.
https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#user-content-ideas-for-domain-specific-properties

**Comment by Hackerpilot** [comment]
It looks like several of the properties that dfmt would need are not standardized by EditorConfig yet. For example, they haven't decided what the [name of the maximum line length](https://github.com/editorconfig/editorconfig/wiki/Property-research:-maximum-line-length) property should be.

**Comment by MartinNowak** [comment]
It isn't yet fully standardized for more advanced coding. Just go with the most obvious one and add a deprecation later if it wasn't the right choice. Still much better than inventing your own format.

**Comment by Hackerpilot** [comment]
I've done some working integrating the C EditorConfig library into dfmt, but I think I may abandon this in favor of implementing my own EditorConfig parsing in D. Using the C library requires downloading and building it (with CMake), and then linking against libpcre.

**Comment by MartinNowak** [comment]
You might try one of the existing ini parsers.
https://github.com/robik/DIni
https://github.com/burner/inifiled

**Comment by Hackerpilot** [comment]
I already use inifiled for D-Scanner. What I meant was implementing the logic that determines which rules apply to which file types.

**Comment by MartinNowak** [comment]
Ah I see, seems simple enough to reimplement. Applying configs of parent directories might be a bit annoying. Files are matched using an extended glob match (`**` matches across folders) which isn't yet supported by [globMatch](http://dlang.org/phobos/std_path.html#.globMatch).

**Comment by MartinNowak** [comment]
[Issue 14415 – globMatch should support recursive matching (**)](https://issues.dlang.org/show_bug.cgi?id=14415)

**Comment by Hackerpilot** [comment]
This is now implemented.

**Comment by MartinNowak** [comment]
Great news, I'm already happily using dfmt for any new source file.

**Comment by Hackerpilot** [comment]
You should do another pull. I've fixed a few issues with .editorconfig loading.
