### ISSUE TITLE
multiple \n before bracket are not fixed properly

### ISSUE THREAD

**Issue by eyveer** [Hackerpilot/dfmt#124]
input:
```
class Asd
    
    
    
{
}
```

output:
```
class Asd
    
{
}
```

expected:
```
class Asd
{
}
```

**Comment by Hackerpilot** [comment]
The line breaking algorithm is written that way to preserve blank lines that the programmer put in the code intentionally. The logic necessary to determine that you didn't want extra newlines there won't be worth the added complexity.
