### ISSUE TITLE
Why no gdc build?

### ISSUE THREAD

**Issue by kozross** [Hackerpilot/dfmt#131]
Given that I use GDC extensively, I find the lack of this option surprising.

**Comment by Hackerpilot** [comment]
As you pointed out in your other bug report, GDC doesn't support recent versions of the language.

**Comment by Hackerpilot** [comment]
http://gdcproject.org/downloads

Disregard that. There are GDC builds that have 2.066.1 DMD compatibility, but it looks like you are using an older version of GDC.
