### ISSUE TITLE
Whitespace missing after `synchronized`

### ISSUE THREAD

**Issue by dcarp** [Hackerpilot/dfmt#144]
Like the other statements, `synchronized` should also be followed by a whitespace:
```D
synchronized (a)
```
instead of
```D
synchronized(a)
```

**Comment by Hackerpilot** [comment]
When I run dfmt I get this output:

```d
unittest
{
	synchronized (whatever)
		doStuff();
}

synchronized class Stuff
{
}
```

**Comment by dcarp** [comment]
It works as expected in v0.3.2. Probably it was fixed here:
https://github.com/Hackerpilot/dfmt/commit/74400b677cccacae7e0b3093ea428dce3a90323c#diff-38b183c93ed453d5efbf1246ec1a641bR1388

**Comment by Hackerpilot** [comment]
It looks like I forgot to separate that change out into its own commit. When I came back to this bug later I forgot about the change made to fix it.
