### ISSUE TITLE
receive blocks are too dense

### ISSUE THREAD

**Issue by yannick** [Hackerpilot/dfmt#145]
example from a test
```
        receive((TLog l) { tlogBuffer[l.timeid] = l; writefln("deleted tlog %s",
            l.timeid); }, (ulong x) { writefln("received long %d", x); tlogBuffer.remove(
                x); });
```
i think this is not very readable.

**Comment by Hackerpilot** [comment]
This might be one of the cases that I handle by implementing https://github.com/Hackerpilot/dfmt/issues/125

**Comment by Hackerpilot** [comment]
Instead of adding more crazy heuristics and special cases, I'm going to recommend that you use ```/// dfmt off``` and ```// dfmt on``` when line wrapping has special meaning.

**Comment by yannick** [comment]
thats fine.
i just encoutered this and thought it might be an easy fix.
