### ISSUE TITLE
Missing whitespace in object property definition

### ISSUE THREAD

**Issue by dcarp** [Hackerpilot/dfmt#148]
```diff
 class Foo
 {
-    @property Socket socket()
+    @propertySocket socket()
     {
         return this.socket;
     }
}
```

**Comment by Hackerpilot** [comment]
Which version of dfmt are you using? I'm not able to reproduce this.

**Comment by dcarp** [comment]
I'm using 0.3.3 on linux compiled with dmd. Properties of type `bool`, `int`, etc. work as expected, only non-keyword types are affected.
The same happens also with user attributes.

**Comment by Hackerpilot** [comment]
Never mind. I had some local changes.
