### ISSUE TITLE
`\n` is changed to `\r\n` on windows

### ISSUE THREAD

**Issue by yebblies** [Hackerpilot/dfmt#16]
It would be better to keep the original line endings, or at least provide an option to force one style.

I know you can work around it with shell scripts etc but I'd much rather just be able to run it on ddmd with `--inplace`.

**Comment by Hackerpilot** [comment]
I love Windows.

**Comment by Hackerpilot** [comment]
It looks like the only way to do this correctly is to do a preprocessing step where the file is scanned for newlines before lexing.

**Comment by yebblies** [comment]
Yeah, it's probably good enough to find the first '\n' and see if it has a '\r' before it.

Or, I'd be happy with it requiring a switch to use windows line endings, and just defaulting to unix-style.

**Comment by qznc** [comment]
Fixed since v0.3.0, I guess. :thumbsup: 
 Close?

**Comment by Hackerpilot** [comment]
Have you tested it on Windows? I don't remember if I did or not...

**Comment by qznc** [comment]
Nope. No windows available for me.

**Comment by yebblies** [comment]
dfmt just converts `\r\n` to `\n`, which is fine for my use, but probably not for anyone that actually wants CRLF.

**Comment by Hackerpilot** [comment]
I checked the code and found that formatter.simpleNewLine does respect the end_of_line editorconfig property. @yebblies Are you still seeing the problem with the end_of_line configuration set to "crlf"?

**Comment by yebblies** [comment]
Looks good.
