### ISSUE TITLE
Wrong indentation of function declaration containing comments

### ISSUE THREAD

**Issue by dcarp** [Hackerpilot/dfmt#162]
```D
void foo(int foobarbazqux1, /*  */
    int foobarbazqux2, /*  */
    int foobarbazqux3, /*  */
    int foobarbazqux4, /*  */
    int foobarbazqux5, /*  */
    int foobarbazqux6, /*  */
    int foobarbazqux7  /* */
);
```
is formated as:
```d
void foo(int foobarbazqux1, /*  */
int foobarbazqux2, /*  */
int foobarbazqux3, /*  */
int foobarbazqux4, /*  */
    int foobarbazqux5, /*  */
    int foobarbazqux6, /*  */
    int foobarbazqux7 /* */
    );
```

**Comment by Hackerpilot** [comment]
This raises questions like "Why aren't those comments in the 'Params:' section of a ddoc comment", but I'll see what I can do.

**Comment by dcarp** [comment]
:) it is from a C header file translated to D.

**Comment by Hackerpilot** [comment]
Theory: The code that checks for line length sees that this is two lines worth of text (as you can see from the fact that there are two levels of indentation), but the code that handles comments is inserting newlines that the indentation algorithm isn't expecting.
