### ISSUE TITLE
Bad indentation inside anonymous functions when using end-of-line comments

### ISSUE THREAD

**Issue by idanarye** [Hackerpilot/dfmt#166]
I'm using end-of-line comments to prevent dfmt from joining lines. This causes some weird results when combined with anonymous functions:
```
$ echo '
$ echo '
void foo() { //
    void bar() { //
        baz({ //
            qux(); //
        }); //
    } //
} //
' | dfmt --brace_style otbs
void foo() { //
    void bar() { //
        baz({  //
        qux(); //
    }); //
} //
}
 //
```

Starting from `qux()`, all lines are one indentation less than what they should be:

 - `qux` has same indentation as `baz`
 - The closing `})` of the `baz` invocation has the same indentation as the `bar` declaration
 - The closing `}` of the `bar` declaration has the same indentation as the `foo` declaration
 - The closing `}` of the `foo` declaration has correct indentation - but that's only because you can't indent less...

**Comment by Hackerpilot** [comment]
I'm not sure if you knew this, but you can insert `// dfmt off` and `// dfmt on` comments to disable formatting for some blocks of code.

**Comment by idanarye** [comment]
I'm trying to use dfmt for indentation - `//dfmt off` doesn't help here because it distables indentation calculation for the opted-off part:
```
$ echo '
// dfmt off
void foo() {
    void bar() {
        baz({
// dfmt on
            qux();
        });
    }
}
' | dfmt --brace_style=otbs
// dfmt off
void foo() {
    void bar() {
        baz({
// dfmt on
qux();
});
}
}
```

**Comment by Hackerpilot** [comment]
I meant that you should put `// dfmt off` before the opening braces and `//dfmt on` after the closing braces. If you enable formatting like this the formatter will try to match the indent level of the closing braces with the opening braces that you told it to ignore.
