### ISSUE TITLE
Weird interplay in FormatVisitor

### ISSUE THREAD

**Issue by qznc** [Hackerpilot/dfmt#172]
I tried dog-fooding dfmt. Here is a weird effect in FormatVisitor reduced. In the following the line break before ":ASTVisitor" is wrong.
```d
final class FormatVisitor
    : ASTVisitor
{
    this(ASTInformation* astInformation)
    {
        this.astInformation = astInformation;
    }
}
```
Shortening anything in the constructor makes the line break disappear. For example:
```d
final class FormatVisitor : ASTVisitor
{
    this(ASTInformation* astInformation)
    {
        this.astInformation = x;
    }
}
```

**Comment by qznc** [comment]
I'm working on this, but I'm hitting a wall because I don't have enough RAM for a debug build. In my branch I added some comments to understand the line breaking algorithm.

https://github.com/Hackerpilot/dfmt/compare/master...qznc:fix172

The bug is probably in "wrapping.d", but I have not located where the costs go wrong.

**Comment by Hackerpilot** [comment]
You mean that DMD uses too much RAM, or the build itself uses too much?

**Comment by Hackerpilot** [comment]
The problem could be that the behavior of `expressionEndIndex` is causing the line wrapping code to look at more tokens than it should.

**Comment by qznc** [comment]
DMD problem. That should improve once we get a D implementation, no?

**Comment by Hackerpilot** [comment]
It should eventually. You're probably running into the problem that memory allocated during CTFE is never freed. The lexer generator used by dfmt uses a lot of CTFE.

**Comment by qznc** [comment]
Regarding expressionEndIndex: At the colon it regenerates line break hints and end index is the end of file. Does not look wrong to me.

Why is the cost lower, if it inserts a line break right away? Why does the cost change, if I shorten an identifier several lines later?

**Comment by qznc** [comment]
expressionEndIndex at semicolon.
No line break: cost == 1200 due to longPenalty (line length 110)
Line break at colon: cost == 1000 (200 + 800), no longPenalty

expressionEndIndex should probably be the first open-brace, but in general braces can be part of an expression (function literals).

**Comment by qznc** [comment]
Ok, here is a real problem: chooseLineBreakTokens overestimes line lengths, because it does not recognize mandatory line breaks (in this test case, the braces). Of course, a line break at the colon makes sense, if you believe the next line break is at the semicolon.

I'm trying to fix this issue without changing too much, the problem is: If expressionEndIndex splits at the open-brace, then tests/issue0153.d fails:

```d
class Foo(T) : FirstInterfaceWithVeryLongName,
    SecondInterfaceWithVeryLongName if (is(T : Bar))
{
    void foo()
    {
    }
}
```

Instead of this reference output, there is no line break between the two long identifiers. The line is still below the hard line length limit with 92 characters. Only with the class body it gets over 120 characters, which explains the current behavior. Maybe we should consider this test case incorrect?

This whole expressionEndIndex guestimation seems fishy to me. I recently wrote down [my thoughts on code formatting](http://beza1e1.tuxen.de/articles/formatting_code.html). My strategy would be: Split token stream into chunks, where we must break the line (e.g. due to Allman brace style). Then format each chunk like chooseLineBreakTokens does. This chunking seems more reasonable than the expressionEndIndex approach.

If we want wrapping.d to properly recognize mandatory line breaks, we need to pass astInformation in there and it gets more complex. Probably, it also duplicates logic, because mandatory line breaks are already handled in formatter.d.

**Comment by Hackerpilot** [comment]
The purpose of `expressionEndIndex` is "split token stream into chunks".

> Instead of this reference output, there is no line break between the two long identifiers. The line is still below the hard line length limit with 92 characters. Only with the class body it gets over 120 characters, which explains the current behavior. Maybe we should consider this test case incorrect?

That's reasonable. Check the "issue-172" branch.

**Comment by qznc** [comment]
"issue-172" branch looks good to me.

**Comment by Hackerpilot** [comment]
I merged that branch to master, so I'm closing this.
