### ISSUE TITLE
Format calls with lots of inputs more neatly.

### ISSUE THREAD

**Issue by clawconduce** [Hackerpilot/dfmt#198]
When a call has lots of inputs, I think it's more readable to put each input parameter on a separate line.

For example:

```
                outfile.write(LOG_FMT, header.service, header.name, header.route,
                    header.elapsed_time_ms, status_names[header.status],
                    header.message_id, header.client_id, header.user_id);
```

versus

```
                outfile.write(LOG_FMT, 
                              header.service,
                              header.name,
                              header.route,
                              header.elapsed_time_ms,
                              status_names[header.status],
                              header.message_id,
                              header.client_id,
                              header.user_id);
```

The general idea is that when there are too many arguments they blend together and it's harder to read, especially if there are `.` mixed in with the `,`s.

I don't have an exact rule in mind.  My first guess would be if there are > 2 lines of arguments - taking into consideration that indented lines have less space per line so they will take up more lines - put 1 argument per line.

**Comment by Hackerpilot** [comment]
I don't have an exact rule in mind.
Well, to implement this feature I'd have to make up an exact rule.

**Comment by rsw0x** [comment]
>Well, to implement this feature I'd have to make up an exact rule.

add an option to break one line per parameter if the function goes beyond the line limit length?

e.g, with a line limit length of 80

    outfile.write(LOG_FMT, header.service, header.name, header.route) //OK, 66 characters


    outfile.write(LOG_FMT, header.service, header.name, header.route,header.elapsed_time_ms, status_names[header.status],header.message_id, header.client_id, header.user_id);//not OK, way past 80

→

    outfile.write(LOG_FMT, 
                  header.service,
                  header.name,
                  header.route,
                  header.elapsed_time_ms,
                  status_names[header.status],
                  header.message_id,
                  header.client_id,
                  header.user_id);

**Comment by clawconduce** [comment]
I was leaning towards having a `max_unalinged_arg_lines` and default it to 2.

If there are more than `max_unalinged_arg_lines` lines of arguments, then the args are automatically setup 1 per line.  If it were set to 1, it would be the same as hitting the line length limit: when the line limit is hit, a 2nd line is added, so it would be >1 lines, and kick off the 1 per line formatting.

**Comment by clawconduce** [comment]
I think this is too subjective to make a rule.  For lots of short arguments they look better on the same line (something like a.x, a.y, a.z, a.t).
