### ISSUE TITLE
Copy stdin to stdout upon commandline error.

### ISSUE THREAD

**Issue by JohanEngelen** [Hackerpilot/dfmt#200]
Currently, when an error happens (e.g. commandline option is not recognized), nothing is output to stdout. This is a little annoying for integration into an editor, where the editor will replace text (passed through stdin to dfmt) with text from stdout. The result is that text is removed completely in the editor when an error happens, instead of nothing happening to the text.
I think when input comes from stdin (as opposed to coming from a file), it is better to copy stdin to stdout in case of an error.

**Comment by Hackerpilot** [comment]
Don't you mean "copy stderr to stdout"? What prevents the editor from capturing stderr?

**Comment by JohanEngelen** [comment]
No, I meant copy stdin to stdout. Basically be transparent upon error. That's what clang-format does. But for the editor script that I'm working on, it actually doesn't matter. It can check for the returnvalue to see if it needs to replace text or not.
