### ISSUE TITLE
Provide means to load config from .editorconfig if readFromStdin is true.

### ISSUE THREAD

**Issue by shishkander** [Hackerpilot/dfmt#240]
After refactoring [0f7727e](https://github.com/Hackerpilot/dfmt/commit/0f7727e31b183cd158a3b04c412421348c0c3c5e), **dfmt** isn't looking for `.editorconfig` files using current working dir when data is passed through stdin.

Basically, `cd /path/src && dfmt <some_d_code_stream` used to load `/path/.editorconfig` if it existed. Now it doesn't.

Temporary workaround for myself is [here](https://github.com/shishkander/dfmt/commit/970269d6ca59c2468851af1e2b32486426b18737).

I will create a pull request if you tell me preferred approach. Alternatives I have in mind so far:

1. my quick and dirty fix above
2. new option to specify config
3. new option to specify directory from which to start looking for configs

Btw, the function [createFilePath](https://github.com/Hackerpilot/dfmt/blob/master/src/dfmt/main.d#L232) is dead code for now.

**Comment by BBasile** [comment]
Option 2 sounds better for me.
