### ISSUE TITLE
Locate .editorconfig files

### ISSUE THREAD

**Issue by StefanHub** [Hackerpilot/dfmt#245]
I am using DFMT with DDT (Eclipse Plugin) and my .editorconfig file does not get found.
DDT just calls DFMT with the --inplace option. In that case DFMT tries to locate the .editorconfig file from the getcwd(). This might be a good option if DFMT is called from the shell but if it is called from inside another tool the getcwd() is no longer predictable.
I have read the documentation of EditorConfig and I think their way of locating the .editorconfig file(s) makes much more sense to me: http://editorconfig.org/#file-location

If a editorconfig can not be found in getcwd() the "standard" way shouuld be tried.

**Comment by Hackerpilot** [comment]
dfmt only checks `getcwd` in these cases:
* Input is being read from stdin
* The path specified to dfmt is not an absolute path

How do you propose that I correctly determine the location of the .editorconfig file in these cases?

**Comment by StefanHub** [comment]
It seems that DDT is calling DFMT with the options/args "--inplace", "." ([Java source](https://github.com/DDT-IDE/DDT/blob/423e66cd5f5e089b36216f9ef97ba24444c444ef/plugin_ide.ui/src/mmrnmhrm/ui/navigator/DeeNavigatorActionProvider.java)). In this case (not an absolute path) DFMT will use the `getcwd`.
I will post an issue on the DDT project to get this clarified.

**Comment by StefanHub** [comment]
So finally I found the reason for the strange behavior. DFMT was not build correctly.
Building with make (DMDs make) fails with
`Error on line 3: '=' is not a valid filename char`
Building with build.bat works sometimes, sometimes not
But with DUB I could create an executable that now works.

What DMD version can be used for building DFMT?

**Comment by Hackerpilot** [comment]
Probably anything less than a year old. I haven't done much testing with old compilers.
