### ISSUE TITLE
Having an import and a comma in an enum clears all code after it

### ISSUE THREAD

**Issue by WebFreak001** [Hackerpilot/dfmt#255]
``` d
enum Foo
{
    import foo,
}
```

Put that at the start of the file, format the file and everything after import foo will be gone

This is invalid syntax but a formatter should just ignore it

**Comment by Hackerpilot** [comment]
This is the behavior that I see:

input:
```d
enum Foo
{
	import foo, 
}

void main(string[] args)
{
}
```
output:
```d
enum Foo
{
	import foo, 
}

void main(string[] args)
{
}
```

Are you running a recent build from git?

**Comment by WebFreak001** [comment]
Uh was probably an old build
