### ISSUE TITLE
Space added after cast

### ISSUE THREAD

**Issue by yebblies** [Hackerpilot/dfmt#31]
```diff
static uinteger_t copySign(uinteger_t x, bool sign)
{
 // return sign ? -x : x;
-    return (x - cast(uinteger_t)sign) ^ -cast(uinteger_t)sign;
+    return (x - cast(uinteger_t) sign) ^ -cast(uinteger_t) sign;
}
```
A quick (and somewhat imprecise) grep seems to show the former is more common in phobos.
```
~/d/phobos$ git grep "cast([^)]\+)[^ ]" | wc -l
2215
~/d/phobos$ git grep "cast([^)]\+)[ ]" | wc -l
469
```

**Comment by yebblies** [comment]
I don't see how this is bikeshedding, you said you want to match phobos style and you're not matching phobos style.

**Comment by Hackerpilot** [comment]
The cast keyword isn't mentioned in the phobos style guide. Brace style and indentation are.

**Comment by yebblies** [comment]
That's why I provided numbers from the source code.  The style guide doesn't cover everything, and existing precedent in the source is used for the rest.

**Comment by yebblies** [comment]
As another point, DMD's expression formatter doesn't write out a space after casts.  This is producing a huge amount of noise in the diffs from running dfmt on DDMD.

**Comment by yebblies** [comment]
I'm not sure why it leaves the first cast alone but adds a space for the second.
```diff
         case cast(structalign_t)1:
             // No alignment
             break;
-        case cast(structalign_t)STRUCTALIGN_DEFAULT:
+        case cast(structalign_t) STRUCTALIGN_DEFAULT:
             // Alignment in Target::fieldalignsize must match what the
```

**Comment by Hackerpilot** [comment]
That inconsistency was fixed in https://github.com/Hackerpilot/dfmt/commit/7f0b3baecbad8d515de06a661c0226c1e3e7825d.
