### ISSUE TITLE
Labels should be outdented once

### ISSUE THREAD

**Issue by yebblies** [Hackerpilot/dfmt#37]
```d
unittest
{
Label:
    {
    }
}
```
```d
unittest
{
    Label:
    {
    }
}
```

**Comment by yebblies** [comment]
Also, libdparse shouldn't be giving an error on a label at the end of a block, which for once is actually [in the grammar](http://dlang.org/statement.html#LabeledStatement).

**Comment by Hackerpilot** [comment]
https://github.com/Hackerpilot/libdparse/issues

**Comment by yebblies** [comment]
I'm still seeing this:
```diff
unittest
{
-    Ldecl:
-    if (decl)
+    Ldecl: if (decl)
    {
    }
}
```
