### ISSUE TITLE
Version statements should have enclosed statement on next line

### ISSUE THREAD

**Issue by yebblies** [Hackerpilot/dfmt#42]
This looks really weird to me:
```diff
         auto r = .strtold(p, endp);
-        version(Windows)
-            __locale_decpoint = save;
+        version (Windows) __locale_decpoint = save;
         return r;
```
Same-line looks ok when used with declarations, but with statements it should probably match what `if`/`while`/`foreach` etc do.

**Comment by Hackerpilot** [comment]
And people said you could make a D formatter without a parser.

**Comment by yebblies** [comment]
People say all sorts of silly things.  This one also probably affects `debug`.
