### ISSUE TITLE
Splitter should avoid splitting inner expressions

### ISSUE THREAD

**Issue by yebblies** [Hackerpilot/dfmt#47]
```diff
     Identifier ident = Identifier.idPool(name);
-    FuncDeclaration* pFd = cast(FuncDeclaration*)dmd_aaGet(&arrayfuncs, cast(void*)ident);
+    FuncDeclaration* pFd = cast(FuncDeclaration*) dmd_aaGet(&arrayfuncs, cast(
+        void*) ident);
     FuncDeclaration fd = *pFd;
```
The entire cast expression should be on the next line.

**Comment by yebblies** [comment]
Another case, the call expression should stay intact.
```diff
-        auto dd = new DtorDeclaration(declLoc, Loc(), stc, Identifier.idPool("__fieldDtor"));
+        auto dd = new DtorDeclaration(declLoc, Loc(), stc, Identifier.idPool(
+            "__fieldDtor"));
```

**Comment by yebblies** [comment]
Another awful one:
```diff
-            memcpy(&saved_idents, &rvl.saved_idents, (const(char)*).sizeof * VC_SAVED_IDENT_CNT);
-            memcpy(&saved_types, &rvl.saved_types, (Type).sizeof * VC_SAVED_TYPE_CNT);
+            memcpy(&saved_idents, &rvl.saved_idents, (const(
+                char)*).sizeof * VC_SAVED_IDENT_CNT);
+            memcpy(&saved_types, &rvl.saved_types, (
+                Type).sizeof * VC_SAVED_TYPE_CNT);
```

**Comment by yebblies** [comment]
New low:
```diff
-        auto ed = new EnumDeclaration(loc, ident, memtype ? memtype.syntaxCopy() : null);
+        auto ed = new EnumDeclaration(loc, ident, memtype ? memtype.syntaxCopy(
+            ) : null);
```

**Comment by Hackerpilot** [comment]
Not as low as the number of pull requests from you.

**Comment by yebblies** [comment]
Should I not be reporting these?

**Comment by Hackerpilot** [comment]
I'm curious what message you are trying to communicate by using the phrases "awful" and "new low".

**Comment by yebblies** [comment]
That the code ends up formatted really badly.

**Comment by Hackerpilot** [comment]
The cost calculation for expression wrapping now adds extra penalties to tokens inside of "(", "[", and "{" tokens. I also tweaked several other parameters to the cost function, so line wrapping should be better in general now.

**Comment by yebblies** [comment]
Awesome, I'll check it out.

**Comment by yebblies** [comment]
It does appear to be better in general now.  Some cases could still be better, eg
```diff
-        doCond(e.thisexp) || doCond(e.newargs) || doCond(e.arguments) || applyTo(e);
+        doCond(e.thisexp) || doCond(e.newargs) || doCond(e.arguments) || applyTo(
+            e);
```

**Comment by Hackerpilot** [comment]
I investigated this further and found two issues:

1. The paren depth info used to more heavily weight inner expressions wasn't calculated properly
2. Some code that was supposed to act as a backup and force a newline if the hard column limit was hit was actually running if the soft column limit was hit.
