### ISSUE TITLE
Add detailed configuration support

### ISSUE THREAD

**Issue by Orvid** [Hackerpilot/dfmt#75]
Basically I'm looking for the ability to fine-tune the formatting choices made by dfmt from a config file, JSON being preferable. This means, controlling the spacing after individual keywords, bracketing requirements separated by statement types, and various other spacing options for different expression types. (such as the `cast()` expression :P)

This would also include options such as ensuring there is a comma after the final item in multi-line arrays and enums. (as 2 separate options)

**Comment by Hackerpilot** [comment]
dfmt uses .editorconfig files now.
