### ISSUE TITLE
Label before `while` not positioned correctly

### ISSUE THREAD

**Issue by yebblies** [Hackerpilot/dfmt#76]
```diff
unittest
{
-Label:
-    while(1)
+    Label: while(1)
    {
    }
}
```
Also happens with `for` and others.

**Comment by Hackerpilot** [comment]
I did that on purpose.

**Comment by yebblies** [comment]
Why?

**Comment by yebblies** [comment]
I assume it's because of labelled break and continue.  These labels can also be used for normal `goto`, and they are in every case in DDMD.
