### ISSUE TITLE
Case label inside version block gets indented wrong

### ISSUE THREAD

**Issue by yebblies** [Hackerpilot/dfmt#97]
```diff
unittest
{
    switch(x)
    {
    case 0:
        version (none)
        {
            // Comment
-            case '\n':
+        case '\n':
                 break;
        }
    }
}
```

**Comment by Hackerpilot** [comment]
The output that I get when formatting this is as follows:
```d
unittest
{
	switch (x)
	{
	case 0:
		version (none)
		{
			// Comment
	case '\n':
			break;
		}
	}
}
```
Aligning the "case" with the "switch" is intentional.

**Comment by yebblies** [comment]
Ok well I guess this is an enhancement request then.

**Comment by yebblies** [comment]
Normal labels appear to be aligned with the switch statement too, is that also intentional?

**Comment by yebblies** [comment]
It looks pretty bad when combined with #76
```diff

unittest
{
    switch(x)
    {
    case 0:
        {
-        Label:
-            while(1) {}
+    Label: while(1)
+            {
+            }
            break;
        }
    }
}

```

**Comment by Hackerpilot** [comment]
> Normal labels appear to be aligned with the switch statement too, is that also intentional?

Yes.

**Comment by Hackerpilot** [comment]
The 0.3.0 release will add configuration options, and I think that this should be one of them.

**Comment by yebblies** [comment]
That sounds great.  How are you planning to expose the configuration options?

**Comment by Hackerpilot** [comment]
Not sure yet.
